apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-student-9
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: student-9
  project: default
  source:
    repoURL: https://github.com/sayalipattil27/argocd-katas-training.git  # Update this URL if the helm chart is in a different repo
    targetRevision: HEAD
    path: quotes-flask/helm/quotes-flask
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true